(clear)
(load "C:/TP - SSBBCC/SBC-asesoramiento-laptop/templates/Laptop.clp")
(load "C:/TP - SSBBCC/SBC-asesoramiento-laptop/src/main.clp")
(load "C:/TP - SSBBCC/SBC-asesoramiento-laptop/src/rules/rules_basico.clp")
(load "C:/TP - SSBBCC/SBC-asesoramiento-laptop/src/response.clp")
(reset)
(run)
